/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:80d1afc9fb31208b40896a83af669a88:1db5ed0f5069bad7e14ac15dcd64699a:e88166e2a20edc8416008044882a5e73$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class alphaBoySpriteSheet
	{
		public const string WalkBack0 = "walkBack0";
		public const string WalkBack1 = "walkBack1";
		public const string WalkBack2 = "walkBack2";
		public const string WalkBack3 = "walkBack3";
		public const string WalkBack4 = "walkBack4";
		public const string WalkBack5 = "walkBack5";
		public const string WalkBack6 = "walkBack6";
		public const string WalkBack7 = "walkBack7";
		public const string WalkBack8 = "walkBack8";
		public const string WalkFront0 = "walkFront0";
		public const string WalkFront1 = "walkFront1";
		public const string WalkFront2 = "walkFront2";
		public const string WalkFront3 = "walkFront3";
		public const string WalkFront4 = "walkFront4";
		public const string WalkFront5 = "walkFront5";
		public const string WalkFront6 = "walkFront6";
		public const string WalkFront7 = "walkFront7";
		public const string WalkFront8 = "walkFront8";
		public const string WalkFront9 = "walkFront9";
		public const string WalkLeft0 = "walkLeft0";
		public const string WalkLeft1 = "walkLeft1";
		public const string WalkLeft2 = "walkLeft2";
		public const string WalkLeft3 = "walkLeft3";
		public const string WalkLeft4 = "walkLeft4";
		public const string WalkLeft5 = "walkLeft5";
		public const string WalkLeft6 = "walkLeft6";
		public const string WalkLeft7 = "walkLeft7";
		public const string WalkLeft8 = "walkLeft8";
		public const string WalkRight0 = "walkRight0";
		public const string WalkRight1 = "walkRight1";
		public const string WalkRight2 = "walkRight2";
		public const string WalkRight3 = "walkRight3";
		public const string WalkRight4 = "walkRight4";
		public const string WalkRight5 = "walkRight5";
		public const string WalkRight6 = "walkRight6";
		public const string WalkRight7 = "walkRight7";
		public const string WalkRight8 = "walkRight8";
	}
}