/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:aa77a4504a4e6b6203b0903c07a64b5b:318023c7a4237e4fd4911b76312e7340:ce69dd048b7ed5fe5be105886035eb72$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class walk_front
	{
		public const string Wf00 = "wf00";
		public const string Wf01 = "wf01";
		public const string Wf02 = "wf02";
		public const string Wf03 = "wf03";
		public const string Wf04 = "wf04";
		public const string Wf05 = "wf05";
		public const string Wf06 = "wf06";
		public const string Wf07 = "wf07";
		public const string Wf08 = "wf08";
		public const string Wf09 = "wf09";
		public const string Wf10 = "wf10";
		public const string Wf11 = "wf11";
		public const string Wf12 = "wf12";
		public const string Wf13 = "wf13";
		public const string Wf14 = "wf14";
		public const string Wf15 = "wf15";
		public const string Wf16 = "wf16";
		public const string Wf17 = "wf17";
		public const string Wf18 = "wf18";
		public const string Wf19 = "wf19";
		public const string Wf20 = "wf20";
		public const string Wf21 = "wf21";
	}
}