/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:070905cd7119dfc3935d4fac1d6a337d:390ce45c4539d8c9baef49826bde69a6:a0a1df41056f935c063126711d939bc5$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class unsaved
	{
		public const string Idle001 = "idle001";
		public const string Idle002 = "idle002";
		public const string Jump001 = "jump001";
		public const string Jump002 = "jump002";
		public const string Walk001 = "walk001";
		public const string Walk002 = "walk002";
		public const string Walk003 = "walk003";
		public const string Walk004 = "walk004";
	}
}