/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:d03dea6d210240a32f8769275dbca912:42811d894c1d9cc491595f1aefa87b2e:cbd37b8a94afd0ccb7cfdf31b976583d$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class project
	{
		public const string Sprite0 = "sprite0";
		public const string Sprite1 = "sprite1";
		public const string Sprite2 = "sprite2";
		public const string Sprite3 = "sprite3";
		public const string Sprite4 = "sprite4";
		public const string Sprite5 = "sprite5";
		public const string Sprite6 = "sprite6";
		public const string Sprite7 = "sprite7";
		public const string Sprite8 = "sprite8";
		public const string Sprite9 = "sprite9";
		public const string Sprite10 = "sprite10";
		public const string Sprite11 = "sprite11";
		public const string Sprite12 = "sprite12";
		public const string Sprite13 = "sprite13";
		public const string Sprite14 = "sprite14";
		public const string Sprite15 = "sprite15";
		public const string Sprite16 = "sprite16";
		public const string Sprite17 = "sprite17";
		public const string Sprite18 = "sprite18";
		public const string Sprite19 = "sprite19";
		public const string Sprite20 = "sprite20";
		public const string Sprite21 = "sprite21";
		public const string Sprite22 = "sprite22";
		public const string Sprite23 = "sprite23";
	}
}